export const SET_MUSIC_SUCCESS = 'SET_MUSIC_SUCCESS';
export const SET_MUSIC_START ='SET_MUSIC_START';
export const SET_MUSIC_FAILED = 'SET_MUSIC_FAILED';

export const GET_ARTIST_INF_SUCCESS = 'GET_ARTIST_INF_SUCCESS';
export const GET_ARTIST_INF_START ='GET_ARTIST_INF_START';
export const GET_ARTIST_INF_FAILED = 'GET_ARTIST_INF_FAILED';
export const GET_ARTIST_INF_CLEAR = 'GET_ARTIST_INF_CLEAR';


export const SEARCH_TRACK_START = 'SEARCH_TRACK_START';
export const SEARCH_TRACK_SUCCESS = 'SEARCH_TRACK_SUCCESS';
export const SEARCH_TRACK_FAILED = 'SEARCH_TRACK_FAILED';
export const SEARCH_TRACK_CLEAR = 'SEARCH_TRACK_CLEAR'


